### PR TITLE
Worker patient tables

### PR DESCRIPTION
**Pull request by pandaorb**
Chase changed the default parameter to a non-default parameter back when we were trying to figure out why Node wouldn't run on my compy - I can change that back if necessary but it's not functionally different. I also tried to add a function for generating random numbers and it's not running. Maybe one of you can figure out why it's 'undefined'? Otherwise it's just a few tables following the sample .jst file.

### CODE REVIEW

**Comment by cookjohns** [comment]
I don't have time to check out why the random number generator isn't running, maybe someone can check on that? 

Anyone should be able to merge pull requests, right?

**Comment by acm0055** [comment]
@cookjohns not sure how to resolve conflicts, but this branch should be ready to merge except for the random number function. I believe a missing semi-colon is the problem. @pandaorb at least it is not a colon problem haha. Uhm... and the other piece of code can stay the same, but does not hurt to change. It works with the older node and newer node. The newer node just has easier to read and use syntax. So I used that due to learning it that way.

**Comment by cookjohns** [comment]
Not seeing where the semicolon goes. Can you fix that real quick or tell me where it goes? I probably have the same problem in the the code I just made a pr for as well.

Working on the conflict now. `git status` says that everything is fine, so I'm not sure how to find it, but I'm looking.

**Comment by cookjohns** [comment]
Got it! Found it via command line. Tried merging manually and it told me that there was a conflict in Worker.jst. @pandaorb added the fields that use the random number generator to that file, which already existed in a different form in the master branch.

Essentially, all I need to do is update the file in the master branch to match the one in the pull request and then it should auto-merge. I don't want to put broken code in the master, so @acm0055 can you tell me how to fix the random number generator? After that's done someone can go on and pull this in.

**Comment by cookjohns** [comment]
@acm0055 Maybe just `func: () => Math.floor(Math.random() * 100000);`? That doesn't seem right.

**Comment by acm0055** [comment]
@cookjohns don't worry I have a valid integer gen that works between any two number low and high

**Comment by cookjohns** [comment]
Ok cool. I'm confused though, is that what's in the code? I thought it didn't work as-is.

**Comment by acm0055** [comment]
@cookjohns It is in my gen code commit

**Comment by acm0055** [comment]
It should be in the current code now.

**Comment by cookjohns** [comment]
Sweet. Pulling.

**Comment by cookjohns** [comment]
Check out my pr if you get a chance. Should look very similar.

**Comment by acm0055** [comment]
@cookjohns will check it out tomorrow.

**Comment by cookjohns** [comment]
@acm0055 Thanks!

Conflict with master resolved, using auto-pull and closing.

**Pull request merged**
